README.md
v1/endpoints/get-identity-map.md
v1/endpoints/get-token-generate.md
v1/endpoints/get-token-refresh.md
v1/endpoints/get-token-validate.md
v1/endpoints/post-identity-map.md
v1/endpoints/post-token-logout.md
v1/guides/dsp-guide.md
v1/guides/publisher-client-side.md
v1/sdks/client-side-identity-v1.md

- Correct code block syntax highlight language type (ref: [GitHub's supported language list](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml))
- Make code indentation consistent (I follow existing ones. 4 spaces for JSON & 2 for JavaScript)

Fix minor code block related issues

---

README-ja.md
README.md

A simple language selector has been added in anticipation of this document being translated into multiple languages in the future.

Add language selector

---

api/v1/guides/operator-guide-gcp-enclave.md

adding integration guide for operator GCP enclave package

add gcp enclave doc

---

README.md
api/README.md
api/v1/endpoints/README.md
api/v1/endpoints/get-identity-buckets.md
api/v1/endpoints/get-identity-map.md
api/v1/endpoints/get-token-generate.md
api/v1/endpoints/get-token-refresh.md
api/v1/endpoints/get-token-validate.md
api/v1/endpoints/post-identity-map.md
api/v1/guides/README.md
api/v1/guides/custom-publisher-integration.md
api/v1/guides/dsp-guide.md
api/v1/guides/operator-guide-aws-nitro-enclave.md
api/v1/guides/operator-guide-azure-enclave.md
api/v1/guides/publisher-client-side.md
api/v1/sdks/client-side-identity-v1.md
api/v1/sdks/dsp-client-v1-overview.md

Miscellaneous formatting, wording, and structural updates

Misc formatting, wording, and structural updates

---

api/v1/sdks/client-side-identity-v0.md
api/v1/sdks/client-side-identity-v1.md

Added notes on SDK v0 and v1 compatibility.

SDK v0 and v1 compatibility

---

api/v1/endpoints/get-token-refresh.md
api/v1/endpoints/get-token-validate.md
api/v1/guides/advertiser-dataprovider-guide.md

Made UID2 remapping workflow clearer; added an FAQ on the opt-out handling.

Tc apidocs 841 updates

---

api/v1/sdks/client-side-identity-v1.md
api/v2/guides/custom-publisher-integration.md
api/v2/guides/publisher-client-side.md
api/v2/sdks/client-side-identity.md

Added cross-refs to the v2 sample apps and docs

Tc apidocs 1007

---

api/v2/endpoints/README.md
api/v2/endpoints/post-token-generate.md
api/v2/guides/custom-publisher-integration.md
api/v2/guides/publisher-client-side.md

Updated copy per provided feedback.

implicit opt-in with token/generate calls

---

README-ja.md

- Fixed issue where one could not go back to English page when on Japanese page.

Fix link error

---

api/v2/guides/README.md
api/v2/guides/google-gss-integration.md

Add Google Secure Signal to integration guides summary

add Google Secure Signal to UID2 docs + integration guide summary

---

api/v2/guides/operator-guide-gcp-enclave.md

GCP enclave copy edits

---

README.md

Gwh apidocs 1204 edits overview

---

api/v2/endpoints/post-token-generate.md

Add "policy" parameter to v2 token/generate endpoint

draft: token generation policy

---

api/README.md

minor copy edits to Getting Started

---

api/v1/endpoints/get-identity-map.md
api/v1/endpoints/post-identity-map.md

fix broken links

---

api/getting-started.md
api/v1/endpoints/get-token-generate.md
api/v1/endpoints/get-token-refresh.md
api/v1/guides/README.md
api/v1/guides/advertiser-dataprovider-guide.md
api/v1/guides/custom-publisher-integration.md
api/v1/guides/publisher-client-side-v0.md
api/v1/guides/publisher-client-side.md
api/v1/sdks/client-side-identity-v1.md
api/v2/endpoints/post-token-generate.md
api/v2/endpoints/post-token-refresh.md
api/v2/guides/advertiser-dataprovider-guide.md
api/v2/guides/custom-publisher-integration.md
api/v2/guides/publisher-client-side.md
api/v2/sdks/client-side-identity.md
workflows/workflow-overview-opt-out.md

Fix malformed br tags, minor wording mods, breadcrumb in one file.

fix malformed br tags, minor wording mods

---

api/v2/sdks/summary-sdks.md

fix MD syntax error resulting in broken link in summary-sdks.md

fix MD syntax error on summary-sdks.md

---

api/v1/sdks/client-side-identity-v0.md
api/v2/endpoints/post-token-validate.md

update https://integ.uidapi.com  to https://operator-integ.uidapi.com. (Note: JP files have an extra instance to change)

update https://integ.uidapi.com  to https://operator-integ.uidapi.com

---

README.md
api/v2/getting-started/gs-faqs.md
api/v2/guides/publisher-client-side.md

Added new FAQ file at v2/getting-started/gs-faqs.md
Removed FAQs from initial README.md and from publisher-client-side.md -- pointed to the new file instead.
Added in-file TOC to publisher-client-side.md.

mods to put FAQ file in place

---

README.md
api/v2/getting-started/gs-faqs.md
api/v2/guides/custom-publisher-integration.md
api/v2/guides/publisher-client-side.md

FAQ info removed from README.md, publisher-client-side.md, custom-publisher-integration.md > getting-started\gs-faqs.md
Add in-file TOC in custom-publisher-integration.md.

Gwh apidocs 1210 uid2 iab faq info

---

api/v2/getting-started/gs-faqs.md
api/v2/guides/advertiser-dataprovider-guide.md
api/v2/guides/dsp-guide.md

Move 6 FAQs from advertiser-dataprovider-guide.md to gs-faq.md.
Move 12 FAQs from dsp-guide.md to gs-faq.md.
Add in-file TOC for second level entries to advertiser-dataprovider-guide.md and dsp-guide.md

Gwh apidocs 1210 uid2 iab faq info 02

---

api/v2/endpoints/post-token-generate.md
api/v2/endpoints/post-token-refresh.md

added info re relationship of policy parameter to optout response in token/generate
Added link list for multiple response examples
Removed mentions of SDK docs and links to them per input from BL.

Gwh apidocs 1274 token refresh error example

---

api/v2/endpoints/post-token-refresh.md

additional minor mod to token/refresh

---

api/v2/endpoints/post-identity-map.md

adding identity map policy parameter

add identity map policy

---

api/v2/guides/google-ss-integration.md
api/v2/guides/operator-guide-aws-marketplace.md

Corrections to some terminology based on AT review of draft glossary.

mods based on AT review of draft glossary

---

api/v2/getting-started/gs-faqs.md
api/v2/guides/advertiser-dataprovider-guide.md

Copyedit on advertiser/data provider guide.

additional edits on advertiser/data provider guide

---

api/v2/endpoints/post-identity-map.md
api/v2/guides/advertiser-dataprovider-guide.md

Mods to Advertiser/Data Provider guide

initial edits

---

api/v2/endpoints/post-identity-map.md
api/v2/guides/advertiser-dataprovider-guide.md

Additional review mods re advertiser/data provider guide updates

Additional review mods re advertiser/data provider guide updates

---

api/v2/guides/google-ss-integration.md
api/v2/guides/operator-guide-gcp-enclave.md
package-lock.json

Mods to IAB files based on edits to new glossary file.

edits from glossary mods

---

api/v2/endpoints/post-identity-buckets.md
api/v2/endpoints/post-identity-map.md
api/v2/endpoints/post-token-generate.md
api/v2/endpoints/post-token-refresh.md
api/v2/endpoints/post-token-validate.md
api/v2/summary-doc-v2.md

remove inline fenced blocks in MD

remove inline fenced blocks in MD

---

sharing-page/docs/getting-started/gs-sharing/index.html
sharing-page/docs/getting-started/gs-sharing/sharing.css

Update temporary sharing page text with approved copy.

---

api/v2/getting-started/gs-faqs.md

Mods from KT review of FAQ doc

Mods from KT review of FAQ doc.

---

README.md
api/v2/endpoints/post-identity-map.md
api/v2/endpoints/post-token-generate.md
api/v2/guides/advertiser-dataprovider-guide.md
api/v2/guides/images/resource/advertiser-flow-mermaid.md
api/v2/guides/images/resource/custom-publisher-flow-mermaid.md
api/v2/guides/images/resource/publisher-flow-mermaid.md
api/v2/guides/snowflake_integration.md
api/v2/upgrades/upgrade-guide.md
workflows/workflow-overview-3p-data-provider.md
workflows/workflow-overview-buy-side.md
workflows/workflow-overview-supply-side.md

change PII to DII (global)

---

README.md
api/README.md
api/v2/getting-started/gs-faqs.md
api/v2/guides/dsp-guide.md
api/v2/guides/google-ss-integration.md
api/v2/guides/operator-guide-gcp-enclave.md

Minor adjustments to lead-in copy.

Minor adjustments to lead-in copy.

---

workflows/workflow-overview-opt-out.md

final edits on workflow doc

---

api/v2/README.md
api/v2/endpoints/README.md
api/v2/guides/README.md
api/v2/sdks/README.md
docs/getting-started/gs-account-setup.md
docs/getting-started/gs-api-keys.md
docs/ref-info/glossary-uid.md

Title changes in Getting Started / Add info re client secret in glossary + API Keys / additional manual redirect files / remove unnecessary gitkeep files.

title changes, add client secret, remove gitkeeps

---

docs/guides/operator-guide-azure-enclave.md

Azure Enclave doc, add link from SW

Azure Enclave doc, add link from SW

---

docs/ref-info/glossary-uid.md

mods to glossary title per input from ET.

mods to glossary title

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md
docs/getting-started/gs-environments.md
docs/summary-doc-v2.md

add info re prod and integ require different keys (info from MC).

add info re prod and integ require different keys

---

docs/summary-doc-v2.md

fix broken link

---

docs/guides/custom-publisher-integration.md
docs/sdks/dsp-client-v1-overview.md

update titles of referenced SDKs in the docs

update titles of referenced SDKs in the docs

---

api/README.md
api/v2/README.md
api/v2/summary-doc-v2.md

minor updates to redirect files

minor updates to redirect files

---

docusaurus.config.js

updated docusaurus config to add docs into into the main nav

feat: :sparkles: add docs intro to main nav

---

src/components/HomepageHero/HeroBgAnimation.tsx
src/components/HomepageHero/index.tsx
tsconfig.json

- set a delay on lottie animation
- updated TS config to allow JSON imports to fix ESLint error

Optimize Home Page Hero

---

src/css/custom.scss
src/css/search.scss

- updated theming colors of search bar 
- visually hide the buttons in the search bar

feat: :lipstick: nav search bar styles

---

api/v2/guides/publisher-client-side.md
api/v2/sdks/client-side-identity.md
api/v2/upgrades/upgrade-guide.md
docs/guides/summary-guides.md
docs/sdks/client-side-identity.md

JS SDK name change, additional mods (redirect files, upgrade doc).

JS SDK name change, additional mods

---

docs/guides/snowflake_integration.md

The functions `FN_T_IDENTITY_MAP_EMAIL` and `FN_T_IDENTITY_MAP_EMAIL_HASH` are deprecated in favour of `FN_T_IDENTITY_MAP`. This new function supports phone numbers and optout.

Update Snowflake documentation

---

docs/guides/snowflake_integration.md

Build failed. Removed br tags and made it into an inline list instead.

fix coding error that would not build (br tags in a table)

---

docs/endpoints/post-identity-map.md
docs/endpoints/post-token-validate.md
docs/endpoints/summary-endpoints.md
docs/getting-started/gs-faqs.md

mods to clarify token validate endpoint. Move procedure from FAQs. Other minor copy clarifications.

mods to clarify token validate endpoint

---

docs/overviews/overview-dsps.md
docs/sdks/summary-sdks.md
docs/sdks/uid2-sdk-ref-java.md

updates to clarify functions of Java SDK per input from AT.

updates to clarify functions of Java SDK

---

docs/getting-started/gs-faqs.md
docs/overviews/overview-publishers.md
docs/sdks/summary-sdks.md

Removing comments. Partially trying to debug why the last merge didn't build.

remove comments

---

docs/sdks/summary-sdks.md

minor copy mods to SDK summary page

minor copy mods to SDK summary page

---

src/components/HomepageNews/index.tsx

removed June 2022 AWS announcement.

CORPWEB-2057: new warner bros. discovery article

---

docs/sdks/summary-sdks.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

add SDK summary table, plus audience info in Java SDK doc

add SDK summary table, plus audience info in Java SDK doc

---

docusaurus.config.js
src/components/DocsBanner/styles.module.scss
src/css/_config.scss
src/css/custom.scss
src/css/markdown.scss
src/css/navbar.scss
src/theme/NavbarItem/NavbarCta.tsx

- Replace #fff with #DCDEE1 on dark theme.
- Update code blocks to: #b7c2ea
- Update accent color lemon #cdf200 to the cyan #1cd2de

feat: update dark theme

---

docs/endpoints/post-token-refresh.md

token refresh tweak

---

i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-advertisers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-data-providers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-dsps.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-operators-private.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md

update ja audience-specific banner text

update ja audience-specific banner text

---

docs/guides/custom-publisher-integration.md
docs/sdks/summary-sdks.md
docs/sdks/uid2-sdk-ref-python.md

These updates are for the python SDK changes from the tickets
[UID2-1270](https://atlassian.thetradedesk.com/jira/browse/UID2-1270)
[UID2-970](https://atlassian.thetradedesk.com/jira/browse/UID2-970)

update docs for python sdk changes.

---

docs/sdks/uid2-sdk-ref-python.md

minor mods to notes in python SDK doc

minor mods to notes in python SDK doc

---

i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-auth.md

fix broken link in Japanese gs-auth.md

fix broken link in Japanese gs-auth.md

---

docs/getting-started/gs-auth.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-auth.md

gs-auth.md JP + Eng additional link fixes

gs-auth.md JP + Eng additional link fixes

---

docs/getting-started/gs-sharing.md
docs/sharing/sharing-best-practices.md
docs/sharing/sharing-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-sharing.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/email-contacts.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/participant-info.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/portal-getting-started.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/portal-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/sharing-permissions.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/team-members.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/uid2-sdk-ref-android.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/uid2-sdk-ref-ios.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-best-practices.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-bid-stream.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-implementing.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-use-cases.md

update original sharing page + add an eng tag on English files copied over to the Japanese fileset to avoid broken links. Tag is so they are easy to find.

update original sharing page + add an eng tag on some files

---

docs/endpoints/post-token-generate.md

Correction to wording re optout response, token/generate.

fix to token/generate from SuW

---

docs/sharing/sharing-best-practices.md
docs/sharing/sharing-bid-stream.md
docs/sharing/sharing-implementing.md
docs/sharing/sharing-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-best-practices.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-bid-stream.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-implementing.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-overview.md

mods on sharing doc based on comments from AT and JN

mods on sharing doc based on comments from AT and JN

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-android.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-ios.md

add English GMA docs to JP fileset (+ included eng_jp tag at end of file).

add English GMA docs to JP fileset (+ tag)

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-aws-marketplace.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-azure-enclave.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-gcp-enclave.md
i18n/ja/docusaurus-plugin-content-docs/current/summary-doc-v2.md

updata to Japanese files, sidebar_position values, to make sidebars consistent

updata to ja files to make sidebars consistent

---

docs/guides/mobile-plugin-gma-android.md
docs/guides/mobile-plugin-gma-ios.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-android.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-ios.md

updates to include SS plus minor edit re token wording

updates to include SS plus minor edit re token wording

---

docs/portal/team-members.md
docs/sdks/uid2-sdk-ref-android.md
docs/sdks/uid2-sdk-ref-ios.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/team-members.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/uid2-sdk-ref-android.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/uid2-sdk-ref-ios.md

in mobile SDK docs, add link to GMA plugin docs. + remove comments.

in mobile SDK docs, add link to GMA plugin docs

---

docs/getting-started/gs-api-keys.md
docs/ref-info/glossary-uid.md

add info re security of keys and secrets

add info re security of keys and secrets

---

docs/sdks/client-side-identity.md
docs/sdks/summary-sdks.md
docs/sdks/uid2-sdk-ref-android.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-ios.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

update values from yes/no to supported/not supported in SDK tables

update values from yes/no to supported/not supported in tables

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

Restore commented-out TOC in guides/publisher-client-side.md, removed in troubleshooting build errors last PR.

restore removed TOC

---

docs/endpoints/post-token-validate.md
docs/getting-started/gs-faqs.md
docs/guides/custom-publisher-integration.md
docs/guides/publisher-client-side.md
docs/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/endpoints/post-token-validate.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-faqs.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/custom-publisher-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

combine publisher FAQ sections into one

combine publisher FAQ sections into one

---

i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-faqs.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/advertiser-dataprovider-guide.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/custom-publisher-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/dsp-guide.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-android.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-aws-marketplace.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-azure-enclave.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-gcp-enclave.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/snowflake_integration.md

comment out TOCs in some Japanese files + other minor tweaks

comment out TOCs in some Japanese files

---

docs/guides/snowflake_integration.md

Snowflake doc, clarification re example scenario

Snowflake doc, clarification re example scenario

---

docs/guides/custom-publisher-integration.md
docs/guides/publisher-client-side.md

add links from publisher guides to new FAQ

add links from publisher guides to new FAQ

---

docs/guides/custom-publisher-integration.md
docs/guides/google-ss-integration.md
docs/guides/integration-prebid.md
docs/guides/operator-guide-aws-marketplace.md
docs/guides/operator-guide-azure-enclave.md
docs/guides/operator-guide-gcp-enclave.md
docs/guides/publisher-client-side.md
docs/guides/snowflake_integration.md
docs/guides/summary-guides.md

Guides folder, mods to sidebar wording (add YAML values)

Guides folder, mods to sidebar wording

---

docs/overviews/overview-publishers.md

In publisher overview, heading update re GMA/IMA

minor heading update in publisher overview

---

docs/getting-started/gs-faqs.md

minor copy edits to FAQ doc

---

docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/getting-started/gs-faqs.md

state in doc that policy parameter with value 1 is required + update request examples.

state in doc that policy parameter with value 1 is required

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-validate.md
docs/endpoints/summary-endpoints.md

Minor edits to UID2 docs based on porting various endpoint updates to EUID doc.

Gwh apidocs 1603 10 edits from update euid endpoint files

---

docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md

opt in/optout copy clarifications re policy parameter required.

opt in/optout copy clarifications re policy parameter required.

---

i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md

fix broken link in Japanese FAQ file

fix broken link in Japanese FAQ file

---

docs/guides/google-ss-integration.md

Secure Signals doc, add links to sample applications

Gwh apidocs 1207 secure signals sample application

---

docs/guides/snowflake_integration.md

minor copy edits to Snowflake sharing doc based on edits to AT Snowflake doc.minor copy edits to Snowflake sharing doc

minor copy edits to Snowflake sharing doc

---

docs/guides/dsp-guide.md

DSP guide, mods for opt-out no timestamp

DSP guide, mods for opt-out no timestamp

---

docs/overviews/overview-dsps.md

update header on DSP overview page

update header on DSP overview page

---

docs/getting-started/gs-normalization-encoding.md

update DII heading to remove acronym

update DII heading to remove acronym

---

docs/guides/snowflake_integration.md

Snowflake doc, fix broken link

Snowflake doc, fix broken link

---

docs/getting-started/gs-faqs.md
docs/guides/dsp-guide.md
docs/guides/publisher-client-side.md
docs/intro.md
docs/overviews/overview-advertisers.md
docs/overviews/overview-data-providers.md
docs/overviews/overview-dsps.md
docs/overviews/overview-operators-private.md
docs/overviews/overview-publishers.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

mod to one DSP FAQ plus minor copy edits re FAQ titles and links.

mod to FAQ for DSP plus minor copy edits

---

docs/overviews/overview-publishers.md

Publisher overview page, fix table formatting error

fix table formatting error

---

docs/overviews/overview-publishers.md

edit from KK on publisher overview page (missed on previous check-in).

edit from KK on publisher overview page

---

docs/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md

mod to publisher docs list from KK

mod to publisher docs list from KK

---

docs/guides/integration-prebid.md
docs/guides/mobile-plugin-ima-android.md
docs/guides/mobile-plugin-ima-ios.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-ima-android.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-ima-ios.md
sidebars.js

New doc updates page + few minor edits to other docs.

Gwh apidocs 1680 doc updates page

---

docs/getting-started/gs-faqs.md
docs/guides/summary-guides.md
docs/overviews/overview-advertisers.md
docs/sharing/sharing-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-sharing.md

fix mention of UID in FAQ + global check.

fix mention of UID in FAQ

---

docs/workflows/workflow-overview-opt-out.md

wording correction, policy parm is not optional

wording correction, policy parm is not optional

---

docs/guides/operator-private-gcp-confidential-space.md

GCP edit from TM

---

docs/guides/summary-guides.md

update integration guide titles in summary page

update integ guide titles in summary page

---

docs/guides/operator-guide-aws-marketplace.md

- Update healthcheck section
- Reflect changes made to CloudFormation templates

Update AWS private operator docs

---

docs/portal/portal-overview.md
docs/portal/sharing-permissions.md
docs/sharing/sharing-overview.md
docs/sharing/sharing-use-cases.md

update mentions of partner to participant in sharing docs

update mentions of partner to participant in sharing docs

---

docs/getting-started/gs-faqs.md

FAQ edit from KK

---

docs/guides/publisher-client-side-v2.md
docs/guides/publisher-client-side.md
docs/sdks/client-side-identity-v2.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side-v2.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/client-side-identity-v2.md

copy review on JS SDK integration guide w/queries marked (4)

copy review on JS SDK integration guide w/queries marked

---

docs/ref-info/updates-doc.md

add announcement for JS SDK v3

Gwh apidocs 1742 06 js sdk update announce

---

docs/guides/integration-prebid-advanced.md
docs/guides/integration-prebid.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
sidebars.js

Checking in initial mods from MC (before edits). This should exactly match https://github.com/IABTechLab/uid2docs/pull/327/files#diff-9ea8707f2f0a49706d36628c330ab7dd73954685c6d9766e5b31601f77d11b8e other than it includes an update to sidebars.js for the opt-out file published yesterday.

checking in initial mods from MC (before edits)

---

docs/ref-info/updates-doc.md

add 2 new articles to doc updates page

add 2 new articles to doc updates page

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

fix syntax error

---

docs/guides/integration-prebid.md
docs/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

Integ guides for Prebid and JS SDK: make sample application info a separate section.

integ guides x2 make sample application a separate section

---

docs/getting-started/gs-account-setup.md

to account setup, add info for those with an existing TTD contact.

to account setup, add info re existing TTD contact

---

src/css/navbar.scss

- reduce margin on sub list parents
- reduce padding on 3rd level nested items

feat: update deeply nested nav css

---

docs/overviews/overview-advertisers.md

Add AWS Entity Resolution guide to resource summary on Advertiser Overview page.

add AWS Entity Resolution guide to advertiser resources

---

docs/getting-started/gs-faqs.md

Updated copy with links to new CSTG Prebid guide. Note we can update this FAQ better later when more CSTG content is in place, but this is an improvement for now.

update FAQ re CSTG

---

docs/ref-info/updates-doc.md

adds to documentation updates page

adds to documentation updates page

---

sidebars.js

Restructure intro part of sidebar.

mods to sidebars per input from VL

---

docs/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

JS SDK guide, copy fix in code comment from SW to remove reference to prebid.js

JS SDK guide, copy fix in code comment from SW

---

docs/overviews/overview-advertisers.md
docs/overviews/overview-data-providers.md
docs/overviews/overview-dsps.md
docs/overviews/overview-publishers.md

Mods to intro copy, audience-specific overview pages (just the intro).

Gwh apidocs 1412 edits from vl overview page copy

---

docusaurus.config.js

docusaurus -- add support for C# syntax highlighting

docusaurus -- add support for C# syntax highlighting

---

docs/overviews/overview-data-providers.md
docs/overviews/overview-dsps.md

edits from KK

---

docs/getting-started/gs-faqs.md

add new DSP FAQ, minor FAQ edits

add new DSP FAQ, minor FAQ edits

---

docusaurus.config.js

docusaurus -- add support for Java syntax highlighting

docusaurus -- add support for Java syntax highlighting

---

docs/overviews/overview-publishers.md

fix uncommented note on Publisher Overview page

fix uncommented note on Publisher Overview page

---

docs/getting-started/gs-encryption-decryption.md
docs/sdks/uid2-sdk-ref-python.md
docusaurus.config.js

add Java example for encrypt/decrypt

add Java example for encrypt/decrypt

---

docs/getting-started/gs-encryption-decryption.md

edit to copy for encryption/decryption code samples, from JN

edit to code sample copy, from JN

---

docs/overviews/overview-advertisers.md
docs/overviews/overview-data-providers.md
docs/overviews/overview-dsps.md
docs/overviews/overview-operators-private.md
docs/overviews/overview-publishers.md

landing page edits from VL: wording changes mostly on Publisher page. Also removed extra column in Implementation Resources tables for all audience-specific landing pages.

landing page edits from VL

---

docusaurus.config.js
src/components/HomepageHero/index.tsx
src/theme/DocSidebarItem/Category/index.tsx

- fixes imported docsaurus 3.x sidebar item module
- fixes homepage randomly getting set to light theme

fix: 🐛  docusaurus3x imports

---

docs/guides/mobile-plugin-gma-android.md

fix typo, GMA Android doc

---

docs/ref-info/updates-doc.md

Documentation Updates page, add 2 entries

Documentation Updates page, add 2 entries

---

docs/getting-started/gs-faqs.md

add new FAQ re HIPAA

---

docs/ref-info/ref-operators-public-private.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-operators-public-private.md

add Operator article to doc updates summary page. Also slight tweak to the article.

add Operator article to doc updates list

---

docs/ref-info/glossary-uid.md
docs/ref-info/updates-doc.md

add letters in glossary file

---

docs/sdks/summary-sdks.md

mods to clarify SDK summary page

mods to clarify SDK summary page

---

sidebars.js

sidebar resequence publisher web guides so Prebid guides are together per request from KK.

sidebar resequence publisher web guides

---

docs/endpoints/summary-endpoints.md
docs/getting-started/gs-faqs.md
docs/getting-started/gs-sharing.md
docs/guides/dsp-guide.md
docs/guides/google-ss-integration.md
docs/guides/summary-guides.md
docs/portal/portal-overview.md
docs/ref-info/glossary-uid.md
docs/ref-info/updates-doc.md
docs/sdks/summary-sdks.md
docs/sharing/sharing-bid-stream.md
docs/sharing/sharing-implementing.md
docs/sharing/sharing-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-faqs.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-sharing.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/dsp-guide.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/summary-guides.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/portal-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/summary-sdks.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-bid-stream.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-implementing.md
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-overview.md
sidebars.js

updates for summary page defaults in sidebar. Also minor title changes to summary pages for consistency.

updates for summary page defaults in sidebar

---

docs/ref-info/updates-doc.md

doc update article for Web Integration Overview

doc update article for Web Integration Overview

---

docs/guides/summary-guides.md
docs/overviews/overview-publishers.md

add links to the Publisher Options page

add links to the Publisher Options page

---

docs/ref-info/updates-doc.md

minor mods to whatsnew doc file (add Jira IDs in comment tags for 2024 items).

minor mods to whatsnew doc file

---

docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
sidebars.js

Sidebar, Integration Guides for publishers, add extra level

Sidebar, Integration Guides for publishers, add extra level

---

sidebars.js

sidebar mods to second Prebid item

sidebar mods to second Prebid item

---

docs/sdks/client-side-identity-v2.md
docs/sdks/client-side-identity.md
docs/sdks/uid2-sdk-ref-android.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-ios.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

add API Permission info to SDK docs

add API Permission info to SDK docs

---

docs/ref-info/updates-doc.md

add JS SDK overview to Doc Updates page

add JS SDK overview to Doc Updates page

---

docs/getting-started/gs-normalization-encoding.md

clarify encoding re UTF-8: initial mod pending clarification

---

docs/getting-started/gs-normalization-encoding.md

updates to clarify sequence of info

updates to clarify sequence of info

---

docs/overviews/overview-publishers.md

Publisher Overview page, copy mod re Getting Started testing step

Publisher Overview page, copy mod re Getting Started testing step

---

docs/ref-info/updates-doc.md

to what's new doc, add audience-specific sidebars.

to what's new doc, add audience-specific sidebars.

---

src/components/HomepageHero/index.tsx
src/components/HomepageHero/styles.module.scss
static/img/hero-desktop.svg
static/img/hero-mobile.svg

Issue: The large desktop Lottie animation was pretty resource intensive due to size and causing the browser to crash for some users. 
Fix: Made the SVGs static for now to reduce browser resources used.

Feat: Update Hero SVGs to Be Static

---

docs/endpoints/post-token-generate.md
docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
docs/guides/summary-guides.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md

minor copy edits to UID2 based on review of Prebid docs for EUID

minor copy edits to UID2 based on review of Prebid docs for EUID

---

sidebars.js

temporary fix re items missing from sidebars -- expand SDKs and Sharing group headings.

temporary fix re items missing from sidebars

---

docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
docs/guides/integration-prebid.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md

additional updates based on review of EUID Prebid

additional updates based on review of EUID Prebid

---

docs/getting-started/gs-encryption-decryption.md
docs/getting-started/gs-faqs.md
docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
docs/guides/integration-prebid.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-encryption-decryption.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md

additional UID2 minor edits based on EUID Prebid work

additional UID2 minor edits based on EUID Prebid work

---

docs/guides/custom-publisher-integration.md
docs/guides/google-ss-integration.md
docs/guides/integration-javascript-server-side.md
docs/sdks/client-side-identity.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/custom-publisher-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/client-side-identity.md

Update wording and links in SS docs, to sample applications. US and JA.

Gwh apidocs 1828 update titles in ss doc

---

sidebars.js

Sidebar mod: expand endpoints by default

Sidebar mod: expand endpoints by default

---

docs/getting-started/gs-normalization-encoding.md

normalization article, clarify mentions of ascii

normalization article, clarify mentions of ascii

---

docs/getting-started/gs-faqs.md

add two FAQs re generating of UID2 values

add two FAQs re generating of UID2 values

---

sidebars.js

sidebar mod to restore sharing generated page

sidebar mod to restore sharing generated page

---

docs/getting-started/gs-encryption-decryption.md

encryption/decryption: for Python add note re Windows

encryption/decryption: for Python add note re Windows

---

sidebars.js

add JS SDK overview guide to sidebar

add JS SDK overview guide to sidebar

---

docs/ref-info/updates-doc.md

add JS SDK updates to whatsnew doc

add JS SDK updates to whatsnew doc

---

docs/getting-started/gs-normalization-encoding.md

To normalization doc, add section re normalization tool

add section re normalization tool

---

docs/ref-info/updates-doc.md

to doc updates, add info re hashing tool

to doc updates file add info re hashing tool

---

docs/getting-started/gs-account-setup.md
docs/ref-info/glossary-uid.md

remove glossary definition for CDP

remove glossary definition for CDP

---

docs/ref-info/glossary-uid.md

glossary wording update, info from EP.

glossary wording update

---

docs/guides/operator-private-gcp-confidential-space.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-private-gcp-confidential-space.md

Fixed incorrect placeholder name

Updated the Prod deployment script

---

docs/overviews/overview-advertisers.md
docs/overviews/overview-data-providers.md
docs/overviews/overview-publishers.md

mods to UID2 overview pages based on legal rev EUID to note diffs

mods to UID2 overview pages based on legal rev EUID to note diffs

---

api/v2/upgrades/upgrade-guide.md

upgrade guide, fix links

---

i18n/ja/docusaurus-plugin-content-docs/current/sdks/summary-sdks.md

SDK summary page JA update table only

SDK summary page JA update table only

---

docs/portal/portal-overview.md

fix typo in portal overview

---

docs/guides/integration-javascript-server-side.md
docs/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

fix sidebar wording re integ guides (Prebid vs JavaScript) take 2.

fix sidebar wording re integ guides (Prebid vs JavaScript) take 2.

---

docs/portal/portal-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-credentials.md

make UID2 Portal Overview items into a table

make UID2 Portal Overview items into a table

---

src/components/HomepagePartnersSegment/styles.module.scss
src/css/custom.scss
src/theme/Navbar/Layout/index.tsx

This PR tightens the container and adds a container to the nav bar.

feat: 💄 Update Container Max Width

---

src/theme/Navbar/Layout/index.tsx

This reverts commit f37f1ddf43f37f5cbf87def9950e9d1344523869 and fixed the nav on docs pages

Revert "feat: :lipstick: add container to navbar"

---

docusaurus.config.js

removed redundant footer items and added EUID

feat: Add Euid link to footer

---

docs/guides/custom-publisher-integration.md

additional mod from JaNa

---

docs/sdks/uid2-sdk-ref-csharp-dotnet.md

minor mods to C# SDK doc

---

docs/getting-started/gs-encryption-decryption.md
docs/getting-started/gs-faqs.md
docs/guides/custom-publisher-integration.md
docs/guides/google-ss-integration.md
docs/ref-info/glossary-uid.md
docs/ref-info/ref-operators-public-private.md
docs/sdks/client-side-identity.md
docs/sdks/uid2-sdk-ref-java.md
docs/sharing/sharing-overview.md
docusaurus.config.js
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-encryption-decryption.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/custom-publisher-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-operators-public-private.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/client-side-identity.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/uid2-sdk-ref-java.md

Resolve broken links that are to fragments -- shown up by latest Docusaurus version. Few remaining in the Japanese pending translation help.

resolve broken links to anchors

---

docs/guides/operator-guide-aws-marketplace.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-aws-marketplace.md

add Docusaurus coding for svg file in AWS Private Operator doc.

add Docusaurus coding for svg file in AWS Private Operator doc.

---

docs/guides/integration-aws-entity-resolution.md

AWS entity resolution service role recommendation

---

docs/ref-info/updates-doc.md

whatsnew updates, add sharing info

whatsnew updates, add sharing info

---

docs/getting-started/gs-encryption-decryption.md
docs/guides/publisher-client-side.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
docs/ref-info/glossary-uid.md
docs/sdks/client-side-identity.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

minor mods on UID2 files from Docusaurus work on EUID content, to help make the content more parallel and easier to share.

minor mods from Docusaurus work on EUID

---

docs/ref-info/updates-doc.md

To doc updates page, add announcement for new API Keys page

To doc updates page, add announcement for new API Keys page

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md

minor copy fix in all 5 endpoint docs. Plus added Docu admonition MD coding.

minor copy fix in endpoint doc

---

docs/sdks/uid2-sdk-ref-python.md

changes from https://github.com/IABTechLab/uid2-client-python/pull/31

[UID2-3105] Update python SDK guide with new interface for DSP check

---

docs/ref-info/updates-doc.md

Add to doc updates page: set of 3 mobile integration guides, Client-Side Integration portal page.

add items to Doc Updates page

---

docs/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md

GSS doc, update link to wrong doc (English + JA)

GSS doc, update link to wrong doc (English + JA)

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md
docs/endpoints/summary-endpoints.md

endpoint docs, minor copy edits

endpoint docs, minor copy edits

---

docs/guides/operator-guide-aws-marketplace.md
docs/guides/operator-guide-azure-enclave.md
docs/guides/operator-private-gcp-confidential-space.md
docs/snippets/_private-operator-release-matrix.mdx

Updated the way the built files are referenced to remove the specifics of the name

Update deploy instructions

---

docs/guides/mobile-plugin-gma-ios.md
docs/guides/mobile-plugin-ima-ios.md
docs/sdks/uid2-sdk-ref-ios.md

Minor copy mods on review of PR #567.

minor copy tweaks to PR 567

---

docs/endpoints/post-optout-status.md

opt-out API, remove extra table column

opt-out API, remove extra table column

---

docs/sdks/client-side-identity-v2.md
docs/sdks/client-side-identity.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

minor mods to SDK docs for JS SDK parity with EUID

minor mods to SDK docs for JS SDK parity with EUID

---

docs/sharing/sharing-overview.md
docs/snippets/_mobile-docs-enable-logging.mdx
i18n/ja/docusaurus-plugin-content-docs/current/sharing/sharing-overview.md

- Fix sequencing in iOS code comment (put comment before code).
- Fix typos (bid steam > bidstream)

Small fixes

---

docs/ref-info/glossary-uid.md

add glossary defs client-side, server-side, client-server.

add glossary defs client-side, server-side, client-server

---

docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
docs/guides/integration-prebid.md
docs/snippets/_prebid-add-prebidjs-to-your-site-ja.mdx
docs/snippets/_prebid-add-prebidjs-to-your-site.mdx
docs/snippets/_prebid-storing-uid2-token-in-browser-ja.mdx
docs/snippets/_prebid-storing-uid2-token-in-browser.mdx
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md

define shared content pieces for Prebid docs (Eng+JA)
Note JA snippet must have unique name + be in docs/snippets folder.

define shared content pieces for Prebid docs (Eng+JA)

---

docs/guides/integration-javascript-server-side.md
docs/guides/integration-prebid-server-side.md

sidebar updates for client-server guides

sidebar updates for client-server guides

---

docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/ref-info/glossary-uid.md

Adding glossary entries as links. Tested with A-D to get input.

mods to glossary to add links on terms

---

sidebars.js

Docu sidebar mod: move publisher mobile integration overview to category level per KK.

move mobile overview to different sidebar location

---

docs/getting-started/gs-faqs.md

clarify FAQ re not storing info, UID2, for AS.

clarify FAQ re not storing info, UID2

---

docs/guides/operator-guide-aws-marketplace.md

- Moved import statement to top of file
- Copy update re "contact us"

minor edits to AWS guide

---

docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md
docs/endpoints/summary-endpoints.md

Minor mods to UID2 endpoint doc set due to endpoint parity comparison for EUID.

endpoint parity updates, UID2 mods, 2 done

---

i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-opt-out.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-mobile-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-options-publisher-web.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-dsps.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/portal-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/team-members.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/client-side-identity-v2.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/client-side-identity.md

Review of comments in Japanese files and remove some (not all).

remove unneeded comments in Japanese files

---

docs/category/endpoints-v2
docs/category/integration-guides
docs/category/overview-pages
docs/category/readme.txt
docs/category/sdks
docs/getting-started/gs-api-using
docs/guides/integration-javascript-standard
docs/workflows/readme.txt
docs/workflows/workflow-overview-3p-data-provider
i18n/ja/docusaurus-plugin-content-docs/current/category/sdks
i18n/ja/docusaurus-plugin-content-docs/current/category/workflows

9 redirect files plus 2 new readmes. Everything builds locally but cannot test locally.

add redirect files per request from KaWi

---

docs/category/endpoints-v2
docs/category/endpoints-v2.mdx
docs/category/integration-guides
docs/category/integration-guides.mdx
docs/category/overview-pages
docs/category/overview-pages.mdx
docs/category/sdks
docs/category/sdks.mdx
docs/getting-started/gs-api-using
docs/getting-started/gs-api-using.mdx
docs/guides/integration-javascript-standard
docs/guides/integration-javascript-standard.mdx
docs/workflows/workflow-overview-3p-data-provider
docs/workflows/workflow-overview-3p-data-provider.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/sdks
i18n/ja/docusaurus-plugin-content-docs/current/category/sdks.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/workflows
i18n/ja/docusaurus-plugin-content-docs/current/category/workflows.mdx
package-lock.json

*Changes*
- Files require a file extension - added `.mdx` where necessary
- In mdx files, don't need a `Home` function - removed

fix redirects - add file extension and remove function

---

docs/category/workflows.mdx
docs/workflows/workflow-overview-3p-data-provider.mdx

Add redirects for specific Japanese URLs.

Gwh apidocs 2239 redirects per request 02

---

docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

additional legal edit based on EUID comment from EP

Minor wording mod re legal basis

---

docs/endpoints/post-token-generate.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

Additional mods to Java and Python SDK docs plus add/update comment tags re UID2/EUID diffs, from legal edits

Edits based on additional input

---

docs/guides/snowflake_integration.md

Snowflake doc, mods to clarify diagram -- specifically that DII is not stored in the private tables.

Snowflake doc, mods to clarify diagram

---

docs/guides/snowflake_integration.md
docs/intro.md
docs/overviews/overview-dsps.md
docs/ref-info/glossary-uid.md
docs/ref-info/ref-operators-public-private.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-dsps.md

add glossary term, encryption key, plus links in from other files.

add glossary term, encryption key, plus links

---

docs/guides/mobile-plugin-gma-ios.md
docs/guides/mobile-plugin-ima-ios.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-gma-ios.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/mobile-plugin-ima-ios.md

GMA/IMA plugin docs for iOS, update supported version 0.3.0 > 0.3.2 in English and Japanese files.

GMA/IMA plugin docs, update supported version

---

docs/getting-started/gs-environments.md

In Environments page, expand info re Global Accelerator to address possible concerns re geographical location of processing.

in Environments page, expand info re Global Accelerator

---

docs/ref-info/updates-doc.md

to doc updates list, add mobile Prebid integration

to doc updates list, add mobile Prebid integration

---

docs/getting-started/gs-environments.md

updates re AWS Global Accelerator.

updates re AWS Global Accelerator

---

docs/guides/integration-prebid-mobile-summary.md
docs/guides/integration-prebid.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-mobile-summary.md
sidebars.js

- new Prebid mobile summary doc + associated updates:
- Update to Publisher page (Prebid section)
- Update to Integration Guides Summary page (Prebid section)
- Update to Prebid Overview page (new section at end to link to the new doc)
- New doc, plus a copy in the Japanese file system
- Update to sidebars.js

new Prebid mobile summary doc + associated updates

---

docs/guides/custom-publisher-integration.md
docs/guides/integration-javascript-server-side.md

updates to two JS docs to remove inaccurate wording re single sign-on

updates to JS doc wording re single sign-on

---

docs/guides/integration-prebid-mobile-summary.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-mobile-summary.md

Prebid mobile summary, update title

Prebid mobile summary, update title

---

docs/getting-started/gs-normalization-encoding.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-normalization-encoding.md

add trailing backslash for Screaming Frog fixes (EN+JA fixed) + fix typo in link copy in a JP file.

Gwh apidocs 2375 02 screaming frog fixes

---

docs/guides/dsp-guide.md

To DSP guide, add latency recommendations

To DSP guide, add latency recommendations

---

docs/guides/integration-prebid.md

Fix title + link copy on in-link to Prebid Mobile SDK doc.

Gwh apidocs 2375 03 mobile fix incorrect link title

---

docs/getting-started/gs-credentials.md
docs/guides/integration-javascript-client-side.md
docs/overviews/overview-publishers.md
docs/ref-info/ref-integration-approaches.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-integration-approaches.md
sidebars.js

New standalone page covering client-side, client-server, server-side, at a high level.

new page re the 3 integration approaches

---

docs/overviews/overview-publishers.md
docs/ref-info/ref-integration-approaches.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-integration-approaches.md

- Doc updates page, add two new entries.
- Couple of minor edits.

doc updates page: add 2 new items

---

docs/guides/dsp-guide.md
docs/ref-info/updates-doc.md
docs/sharing/sharing-security.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/dsp-guide.md

- Fixed date format to US format in Documentation Updates.
- Fixed broken link in JA DSP guide + same in corresponding English file.
- Abbreviated description in sharing-security.md

whatsnew, fix date format

---

docs/getting-started/gs-credentials.md
docs/guides/integration-javascript-client-side.md
docs/guides/integration-mobile-client-side.md
docs/guides/integration-prebid-client-side.md
docs/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-side.md

Add new glossary term, client keypair, plus adjust credentials text and add lead-in links.

add new glossary term

---

docs/portal/api-keys.md
docs/portal/client-side-integration.md
docs/portal/email-contacts.md
docs/portal/participant-info.md
docs/portal/portal-overview.md
docs/portal/sharing-permissions.md
docs/portal/team-members.md

- Updates to various UID2 Portal doc pages to reflect reorganization and update.
- Clarified what's needed for mobile app ID
- Added section re security recommendations for API keys.

UID2 Portal doc updates

---

docs/getting-started/gs-faqs.md
docs/ref-info/ref-operators-public-private.md

clarify DII > raw UID2 always same value at same time

clarify DII > raw UID2 always same value at same time

---

docs/guides/google-ss-integration.md
docs/guides/integration-javascript-client-server.md
docs/guides/integration-publisher-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/google-ss-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-publisher-server-side.md

Minor copy updates re sample applications

Updates re sample applications

---

docs/getting-started/gs-credentials.md

To UID2 Credentials doc, add client-server. Plus update doc links.

To UID2 Credentials doc, add client-server

---

docusaurus.config.js
docusaurus.preview.js

- Remove CommonJS `require` & `module.export` in favor of only using ESM `import` & `export`
- add `const` to `config` in `docusaurus.preview.js` to fix preview build

ibg-fix-config-undefined-preview

---

docs/guides/integration-javascript-client-side.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md

replaced https://github.com/IABTechLab/uid2docs/pull/679

Refer to JS SDK 3.4.5 instead of old 3.2.0

---

docs/getting-started/gs-faqs.md
docs/guides/integration-mobile-client-server.md
docs/guides/integration-mobile-client-side.md
docs/guides/integration-mobile-overview.md
docs/sdks/sdk-ref-android.md

In the mobile integration overview, added troubleshooting and FAQ info.

To mobile docs, add FAQ/troubleshooting info

---

docs/ref-info/ref-tokens.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-tokens.md

- Announcements for two new docs, token article and DSP not using SDKs.
- One minor copy mod to site metadata for ref article re token.

two new announcements

---

docs/sdks/sdk-ref-python.md

Using example from https://github.com/IABTechLab/uid2-client-python/blob/main/examples/sample_get_identity_buckets.py

Add Python sdk guide for monitoring salt bucket rotations

---

docs/getting-started/gs-account-setup.md
docs/guides/integration-options-publisher-web.md
docs/overviews/overview-publishers.md
docs/portal/client-side-integration.md
docs/ref-info/ref-integration-approaches.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-account-setup.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-options-publisher-web.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/client-side-integration.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-integration-approaches.md

- Add Android and iOS SDK docs to Publisher Overview page
- Fix broken links introduced from mods to Account Setup page on #686.

add Android and iOS SDK docs to Publisher page

---

docs/ref-info/updates-doc.md

Announcement for Private Operator summary doc
Also tweak some of the titles in the summary doc to reduce right sidebar clutter.

Announcement for Private Operator summary doc

---

docs/ref-info/glossary-uid.md

add statement to glossary def for token

add statement to glossary def for token

---

docs/ref-info/glossary-uid.md

Additional info in glossary def re token, edit from JN

Additional info in glossary def re token, edit from JN

---

docs/guides/google-ss-integration.md

To SS GAM doc, add note re config option

To SS GAM doc, add note re config option

---

docs/ref-info/updates-doc.md

announce new tokens page

---

docs/sharing/sharing-tokenized-from-data-bid-stream.md
docs/sharing/sharing-tokenized-from-data-pixel.md

minor edits to sharing docs

---

docs/endpoints/post-identity-map.md
docs/guides/integration-mobile-client-server.md
docs/guides/integration-prebid-mobile-summary.md
docs/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/endpoints/post-identity-map.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-mobile-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-mobile-summary.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-operators-public-private.md

In Mobile Prebid, add mentions of iOS support

In Mobile Prebid, add mentions of iOS support

---

sidebars.js

remove summary-doc-v2 from sidebar

remove summary-doc-v2 from sidebar

---

api-ja/v2/upgrades/upgrade-guide.md
api/v2/upgrades/upgrade-guide.md

adjustments re admonitions: remove Docusaurus formatting on no-Docusaurus files.

adjustments re admonitions

---

docs/portal/team-members.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/team-members.md

Delete Team Member -> Remove Team Member

Cater for renaming in Portal Team Management

---

docs/guides/integration-prebid-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-server.md

Prebid client-server doc:
- update Sample Token heading per JN
- update cookie example for realistic value

Prebid update for set-cookie info

---

docs/guides/integration-options-publisher-web.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md

minor edits re sample apps, Prebid.js

minor edits re sample apps, Prebid.js

---

docs/guides/google-ss-integration.md
docs/guides/integration-prebid-client-server.md
docs/guides/integration-prebid-client-side.md

- In GAM SS doc, add info re updating Prebid config.
- In both Prebid docs, add an "optional" section linking back for the GAM SS steps.

GAM SS doc, add step to update Prebid config

---

docs/getting-started/gs-faqs.md
docs/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-faqs.md

- Minor edit to remove encoded space in code tag.
- Fix MD indentation on FAQ lists (EN+JA).

minor edit

---

sidebars.js

UID2 sidebar mods:
- Collapsed Endpoints, Tokenized Sharing
- Moved some items GS > ref

UID2 sidebar, move some items GS > ref

---

docs/guides/integration-mobile-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-mobile-overview.md

fix capitalization Cocoapods > CocoaPods in EN and JA files.

fix capitalization Cocoapods > CocoaPods

---

docs/guides/snowflake_integration.md
docs/sdks/sdk-ref-android.md
docs/sdks/sdk-ref-cplusplus.md
docs/sdks/sdk-ref-csharp-dotnet.md
docs/sdks/sdk-ref-ios.md
docs/sdks/sdk-ref-java.md
docs/sdks/sdk-ref-javascript-v2.md
docs/sdks/sdk-ref-javascript.md
docs/sdks/sdk-ref-python.md
docs/sdks/summary-sdks.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/snowflake_integration.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-android.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-cplusplus.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-csharp-dotnet.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-ios.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-java.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript-v2.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-python.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/summary-sdks.md

SDK functionality tables, update column heading

SDK functionality tables, update column heading

---

src/css/_config.scss
src/css/markdown.scss

glossary, increase inter-para spacing by 1px.

glossary, increase inter-para spacing

---

i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-java.md

fixed bid stream

---

docs/guides/operator-guide-aws-marketplace.md
docs/guides/operator-private-gcp-confidential-space.md
docs/ref-info/glossary-uid.md
docs/sdks/summary-sdks.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/summary-sdks.md

minor edits to UID2 docs based on EUID parity check ref-info docs

minor edits from EUID parity on ref-info docs

---

docs/ref-info/updates-doc.md

announce LR doc

---

docs/portal/portal-getting-started.md
docs/portal/portal-overview.md
i18n/ja/docusaurus-plugin-content-docs/current/portal/portal-getting-started.md

add info re system-required password change

add info re system-required password change

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-optout-status.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md
docs/getting-started/gs-normalization-encoding.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md

Minor edits from follow-up compare of Endpoint docs, couple of other minor edits.

minor edits

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-optout-status.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-validate.md
docs/endpoints/summary-endpoints.md
docs/getting-started/gs-sharing.md
docs/guides/advertiser-dataprovider-guide.md
docs/guides/dsp-guide.md
docs/guides/integration-javascript-client-server.md
docs/guides/integration-mobile-overview.md
docs/guides/integration-publisher-server-side.md
docs/guides/operator-guide-aws-marketplace.md
docs/guides/operator-guide-azure-enclave.md
docs/guides/operator-private-gcp-confidential-space.md
docs/ref-info/glossary-uid.md
docs/sharing/sharing-overview.md

Add links in various files to content in Getting Started section and especially ref-info section.

add links to gs and ref-info files

---

docs/ref-info/updates-doc.md

announce zoom-in tool for UID2 site.

announce zoom-in tool

---

docs/portal/api-keys.md

Fix typo causing broken link on Algolia report.

fix typo on link

---

docs/guides/operator-guide-aws-marketplace.md

@sunnywu  had some suggestions after the last MR was merged (See: https://github.com/IABTechLab/uid2docs/pull/792/files) 
Addressing those. 
Also changes error-code to be EXX and not AWXX/AZXX

Update wording, change error code to be generic

---

docs/guides/integration-mobile-client-server.md
docs/guides/integration-mobile-client-side.md

add refs to isloggingenabled in copy for Algolia

add refs to isloggingenabled in copy for Algolia (UID2)

---

docs/guides/integration-prebid-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-server.md

fix some metadata values to ensure sidebar accuracy and parity between the two languages.

fix some metadata values

---

docs/ref-info/updates-doc.md

announce SSO publisher doc

---

docs/ref-info/updates-doc.md

announce expanded advertiser/data provider doc

announce advertiser/data provider expanded doc

---

docs/overviews/overview-publishers.md
package-lock.json
package.json
src/components/DocsBanner/index.tsx
src/components/DocsBanner/styles.module.scss
src/css/markdown.scss
src/theme/DocItem/Layout/index.tsx

Reverts IABTechLab/uid2docs#804

Revert "ibg-TTD-786-banner-tables"

---

package-lock.json
package.json
src/css/markdown.scss

- Add styles to html table headers to match markdown table headers

ibg-TTD-786-tables

---

docs/guides/integration-javascript-client-server.md
docs/sdks/sdk-ref-javascript-v2.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript-v2.md

Updated JS client-server integration example: edits from AS

Updated JS client-server integration example: edits from AS

---

docs/guides/integration-google-ss.md
docs/guides/integration-publisher-server-side.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-google-ss.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-publisher-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md

GSS sample implementations, update domains

GSS sample implementations, update domains

---

docs/overviews/overview-advertisers.md
docs/overviews/overview-data-providers.md
docs/overviews/overview-dsps.md
docs/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-advertisers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-data-providers.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-dsps.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md

overview page banners, customize colors and icons

overview page banners, customize colors and icons

---

docs/getting-started/gs-api-using.mdx
docs/guides/custom-publisher-integration.mdx
docs/guides/integration-javascript-server-side.mdx
docs/guides/integration-javascript-standard.mdx
docs/guides/publisher-client-side.mdx
docs/sdks/client-side-identity.mdx
docs/sdks/uid2-sdk-ref-android.mdx
docs/sdks/uid2-sdk-ref-cplusplus.mdx
docs/sdks/uid2-sdk-ref-csharp-dotnet.mdx
docs/sdks/uid2-sdk-ref-ios.mdx
docs/sdks/uid2-sdk-ref-java.mdx
docs/sdks/uid2-sdk-ref-python.mdx
i18n/ja/docusaurus-plugin-content-docs/current/guides/custom-publisher-integration.mdx

Remove old Docusaurus redirect files.

remove old Docusaurus redirect files

---

docs/guides/integration-google-ss.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-google-ss.md

Add new GSS client-side sample implementation

Add new GSS client-side sample implementation

---

docs/ref-info/updates-doc.md

announce updates re Portal instructions

announce updates re Portal instructions

---

docs/guides/integration-prebid.md
docs/ref-info/glossary-uid.md
docs/ref-info/updates-doc.md

add GDPR definition + fix typo

add GDPR definition + fix typo

---

docs/guides/integration-snowflake.md

minor edits in UID2 Snowflake docs, for consistency

minor edits in UID2 Snowflake docs, for consistency

---

docs/category/dsp-integrations-3.mdx
docs/category/private-operator-integrations-1.mdx
docs/category/private-operator-integrations-2.mdx
docs/category/private-operator-integrations-3.mdx
docs/category/private-operator-integrations-4.mdx
docs/category/private-operator-integrations.mdx
docs/getting-started/gs-api-using.mdx
docs/guides/integration-prebid-server-side.mdx
docs/guides/publisher-client-side.mdx
docs/overviews/overview-operators-private.mdx
docs/sdks/client-side-identity.mdx
docs/sdks/uid2-sdk-ref-java.mdx
docs/workflows/workflow-overview-supply-side.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/dsp-integrations-3.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/dsp-integrations-4.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/mobile.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/private-operator-integrations-1.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/private-operator-integrations-3.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/private-operator-integrations-4.mdx
i18n/ja/docusaurus-plugin-content-docs/current/category/private-operator-integrations.mdx
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.mdx
i18n/ja/docusaurus-plugin-content-docs/current/guides/snowflake_integration.mdx
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-operators-private.mdx

redirects per request from KW in Marketing

redirects per request from Marketing

---

docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/getting-started/gs-encryption-decryption.md
docs/getting-started/gs-faqs.md
docs/guides/integration-ctv-guide.md
docs/guides/integration-google-ss.md
docs/guides/integration-javascript-client-server.md
docs/guides/integration-javascript-client-side.md
docs/guides/integration-javascript.md
docs/guides/integration-mobile-client-server.md
docs/guides/integration-mobile-client-side.md
docs/guides/integration-mobile-overview.md
docs/guides/integration-prebid-client-server.md
docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid.md
docs/guides/integration-publisher-server-side.md
docs/guides/operator-guide-aws-marketplace.md
docs/guides/operator-guide-azure-enclave.md
docs/guides/operator-private-gcp-confidential-space.md
docs/overviews/overview-publishers.md
docs/ref-info/ref-integration-sso-providers.md
docs/sdks/sdk-ref-javascript-v2.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-integration-sso-providers.md

- update snippet paths to be relative paths
- Minor heading capitalization fix re "In"

update snippet paths to relative

---

sidebars.js

To sidebar, add new grouping, "UID2 Participants"

To sidebar, add participants grouping

---

src/theme/DocSidebarItem/index.tsx
src/theme/DocSidebarItem/styles.css

- Add style overrides to the sidebar nav to unify spacing between different level links

ibg-CORPWEB-3430-nav-spacing

---

docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/updates-doc.md

Mods to doc updates page:
- In the titles, remove New and Updated, for brevity.
- Add quarterly H2 tags to break it up.

doc updates page mods

---

docs/ref-info/updates-doc.md

add announcements: AKS private operator guide, server-side integration guide for mobile.

add announcements

---

docs/guides/integration-javascript-client-server.md
docs/guides/integration-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-aks-enclave.md

refresh AKS JA copy + minor edits

refresh AKS JA copy + minor edits

---

docusaurus.config.js
i18n/ja/docusaurus-theme-classic/footer.json

added link to footer and japanese translation.

add link in footer

---

docs/ref-info/glossary-uid.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/glossary-uid.md

fix additional links in glossary

fix additional links in glossary

---

docs/guides/integration-javascript.md
docs/guides/integration-options-publisher-web.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-options-publisher-web.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/summary-guides.md
i18n/ja/docusaurus-plugin-content-docs/current/overviews/overview-publishers.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/updates-doc.md

1) Modify name, Publisher Web Options page
2) resequence import statements in one file

Modify name, Publisher Web Options page

---

docs/portal/portal-overview.md

To the Getting Started doc for the UID2 Portal, add portal URL.

add portal URL

---

docs/sdks/sdk-ref-java.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-java.md

fix typo in Java SDK doc

---

.gitignore
README.md
src/components/CustomTags/CustomTagsContainer.tsx
src/components/CustomTags/CustomTagsContext.tsx
src/components/CustomTags/CustomTagsFilterList.tsx
src/components/CustomTags/CustomTagsFilters.tsx
src/components/CustomTags/styles.module.scss
src/theme/Layout/Provider/index.tsx
tsconfig.json

Added the ability to add custom tags to any markdown page. See the README.md instructions for implementation details.

ibg-CORPWEB-3558-update-custom-tags

---

docs/ref-info/updates-doc.md
src/components/CustomTags/CustomTagsContainer.tsx
src/components/CustomTags/CustomTagsContext.tsx
src/components/CustomTags/CustomTagsFilterList.tsx
src/components/CustomTags/styles.module.scss

- Custom tags should now wrap on smaller screens
- An "All" tag has been added by default

Custom tags fix

---

package-lock.json
package.json

- Update all minor versions and run vulnerability check

Dependency Update

---

docs/getting-started/gs-faqs.md
docs/guides/integration-ctv-guide.md

add best practices for CTV integrations. Plus minor mods to FAQ file.

add best practices for CTV integrations

---

docs/guides/operator-guide-aks-enclave.md
docs/ref-info/deprecation-schedule.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/deprecation-schedule.md

- AT edit to deprecation page: move Upgrade Policy section withing Private Operator Versions section.
- Add note on AKS doc re contact info to get started

AT edit + add AKS note re contact for help

---

sidebars.js

sidebar mod to expand Endpoints

sidebar mod to expand Endpoints

---

docs/endpoints/post-identity-map-v2.md

add link to deprecation schedule from v2 POST /identity/map doc.

add link to deprecation schedule

---

docs/guides/integration-snowflake-previous.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-snowflake-before-february-2025.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-snowflake-previous.md

Snowflake doc. One sidebar mod to more closely match previous treatment. One minor edit in note, for consistency.

Snowflake doc, tweaks

---

docs/ref-info/deprecation-schedule.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/deprecation-schedule.md

fix formatting on deprecation notice

fix formatting on deprecation notice

---

docs/endpoints/post-identity-map.md

In POST /identity/map file, update resources section to include latest doc links.

POST /identity/map, update resources section

---

docs/endpoints/post-identity-map.md

remove HTML comment in POST /identity/map resources section.

remove comment
