api/README.md

The SHA256 and base64 examples appeared incorrect according to https://emn178.github.io/online-tools/sha256.html , as well as when debugging Operator manually.

fix phone hashing examples

---

api/v2/guides/README.md

Adding link to Guides summary table for Google Cloud Platform Confidential Compute doc.

add link in guides readme to Google Cloud Platform Confidential Compute

---

api/README.md

Clarify the need for publishers to normalize initial PII before hashing.

Gwh apidocs 1217 normalization need clarify uid2

---

README.md

Restore copy from 1/11/23 version for advertising token definition, to correct error.

correction to initial readme

---

api/v2/upgrades/upgrade-guide.md

I noticed this link currently is broken.

Fix contact-info link in upgrade-guide

---

README-ja.md
api-ja/v1/README.md

After taking down v1 files in English, link check in Docusaurus showed 2 broken links. They might work in Git but the Japanese files will be going to Docusaurus soon anyway. Fixed them so all links are good.

fix broken links in JP files

---

src/components/HomepageHero/styles.module.scss

This PR fixes on FF the hero BG not aligning to the right side of the screen

fix: :bug: firefox desktop hero bg alignment

---

docs/endpoints/post-identity-buckets.md
docs/endpoints/post-identity-map.md
docs/endpoints/post-token-generate.md
docs/endpoints/post-token-refresh.md
docs/endpoints/post-token-validate.md
docs/getting-started/gs-api-keys.md
docs/getting-started/gs-environments.md
docs/ref-info/glossary-uid.md
docs/summary-doc-v2.md

Mods to glossary and other files to make API key the primary term

make API key the primary term

---

docs/ref-info/glossary-uid.md

Add "API secret" to glossary as a cross-referenced term.

glossary add (API secret)

---

docs/ref-info/glossary-uid.md

Typo fix in glossary (missing parens).

glossary typo fix

---

docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

Fixed some sections that were tagged with h1, should be h2.

fix heading tags on SDK docs

---

docs/sdks/client-side-identity.md
docs/sdks/uid2-sdk-ref-cplusplus.md
docs/sdks/uid2-sdk-ref-csharp-dotnet.md
docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

updates to left nav metadata for SDK guides so left nav and landing page copy is shorter and more parallel.

updates to left nav metadata for SDK guides

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

The TOC in the Japanese file, which I restored in the last PR, was, actually, causing a problem. Removed it again.

remove commented-out TOC in Japanese file

---

i18n/ja/code.json

**Change from ‘管理’ to ‘UID2を管理’**
**Change from ‘アクセスをリクエストする‘ to ‘導入についてお問合わせ’**

fix: :bug: update Japanese homepage CTAs

---

i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

fix coding error in JPN publisher-client-side.md

fix coding error in JPN publisher-client-side.md

---

docs/guides/integration-prebid-advanced.md
docs/guides/integration-prebid.md
docs/guides/summary-guides.md
docs/overviews/overview-publishers.md
docs/ref-info/updates-doc.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid.md
static/examples/cstg-prebid-example/README.md
static/examples/cstg-prebid-example/index.html

replace Cstg description with something more generic and renamed prebid integration guide to Prebid.js Express Integration Guide so it's easier to differentiate between the normal/Express guide versus the Advanaced Integration guide (calling it Standard/default doesn't sound as nice/quick as Express

UID2-1411 replace Cstg description with something more generic

---

docusaurus.config.js

Refactored the Japanese version of the site to use `ja`  instead of  `jp-JP` in the HTML land attribute. This should fire the one trust banner in Japanese now.

refactor: :recycle: update HTML lang attr for ja

---

src/components/DocsBanner/index.tsx

If the <DocsBanner> component is displayed, it will remove the duplicate header + h1 below it automatically generated by Docusaurus.

fix: :bug: remove duplicate header + h1 from docs

---

docs/guides/operator-private-gcp-confidential-space.md

added code back ticks on 2 placeholder values that had curly brackets causing build exceptions in Docusaurus 2.

added code back ticks on 2 placeholder values

---

docs/endpoints/post-identity-map.md
docs/getting-started/gs-faqs.md

FAQ mods based on EUID edits from EP + minor update to endpoint description for POST identity/map.

FAQ mods based on EUID edits from EP

---

i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-encryption-decryption.md

Fixed a bug in gs-encryption-decryption.md where C# code was not displayed.

fix error in MD syntax in jpn translation update #398

---

docs/sdks/summary-sdks.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/summary-sdks.md

SDK summary page functionality table, add footnote + minor mods

SDK summary page functionality table, add footnote + minor mods

---

docs/getting-started/gs-auth.md
docs/getting-started/gs-encryption-decryption.md
docs/guides/integration-prebid-client-side.md
docs/guides/integration-prebid-server-side.md
docs/guides/publisher-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-prebid-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/publisher-client-side.md

Adjustments to Getting Started articles to accommodate CSTG.

Gwh apidocs 1786 cstg minor mods

---

docs/sdks/uid2-sdk-ref-java.md
docs/sdks/uid2-sdk-ref-python.md

mods to Java SDK doc to add publisher info

mods to Java SDK doc to add publisher info

---

src/theme/Layout/Provider/index.tsx

Changed `src/theme/Layout/Provider/index.js` to `src/theme/Layout/Provider/index.tsx` and cleaned up minor TS warnings on the page

refactor: :recycle: Convert swizzled theme provider to TS

---

docs/getting-started/gs-account-setup.md
docs/guides/integration-prebid-client-side.md
docs/guides/publisher-client-side.md

bold wording domain names, 3 instances, KL request.

bold wording domain names, 3 instances

---

docs/sdks/uid2-sdk-ref-csharp-dotnet.md

- Update documentation for .NET SDK version 5.6.0
- Document use of BidstreamClient and SharingClient
- Document encryption response content
- Add "Usage for DSPs" section
- Link to full examples in the .NET SDK repo

Update .NET SDK documentation to add usage for DSPs

---

sidebars.js

Two sidebar mods:
- JS SDK integration guide, make overview page display at top level not on sidebar (no generated page, like Prebid)
- SDKs: Remove SDKs from audience-specific exception lists, change initial display to collapsed. So all audiences see the full list.

sidebar, 2 mods

---

static/robots.txt

Looks like some weird URLs related to careers job postings are being generated and creating "new" URLs that google is crawling and linking to UID2 which google search console is flagging. While we do have canonical URLs in place which already solves this issue,  we can also disallow the pages from being indexed. 
`Disallow: /*?`
This will effectively prevent Google from crawling any parameterized URL in the future which should lead to fewer of these issues popping up which has been added to the robots.txt

feat: :mag: stop indexing of URL params

---

src/pages/partners.tsx

The page_view event was firing four times because it was originally in the wrong function.
Moved it to the page component and is now firing once.

fix: :bug: GTM event firing 4 times on page load

---

src/pages/index.tsx
src/pages/partners.tsx
src/pages/request-access.tsx
src/theme/BlogListPage/index.tsx
src/theme/DocItem/Layout/index.tsx

Issue: There was a slight delay in the document updating between page routes which was causing analytics to have the wrong document titles being reported 
Fix: add a slight delay to the firing of the page load event to wait for the document to propagate.

fix: :chart_with_upwards_trend: document title being sent to GTM

---

docs/ref-info/ref-tokens.md
i18n/ja/docusaurus-plugin-content-docs/current/ref-info/ref-tokens.md

Tokens ref article: Remove specific class name in new section about token refresh. Two SDKs are referenced and the class name is different in each, so, made the copy generic.

new tokens section, remove class name

---

docs/guides/operator-guide-aws-marketplace.md
docs/sdks/sdk-ref-csharp-dotnet.md

AWS doc edit from TM, other minor typographical edits

AWS doc edit, other minor typographical edits

---

docs/getting-started/gs-faqs.md

FAQ re testing token refresh workflow: update example to include actual values

FAQs: update example to include values

---

docs/getting-started/gs-faqs.md
docs/guides/integration-google-ss.md
docs/guides/integration-javascript-client-server.md
docs/guides/integration-javascript-client-side.md
docs/guides/integration-publisher-server-side.md
docs/sdks/sdk-ref-javascript.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-google-ss.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-javascript-client-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-publisher-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/sdks/sdk-ref-javascript.md

Standardize headings and wording for sample implementations referenced in the docs.

Gwh apidocs 2801 sample apps standardize uid2

---

docs/guides/integration-prebid-client-side.md
docs/ref-info/glossary-uid.md
docs/sdks/sdk-ref-javascript.md

minor edits to address Algolia no-hits report

minor edits to address Algolia no-hits report

---

docs/guides/integration-publisher-server-side.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-publisher-server-side.md

minor edit re sample application

minor edit re sample application

---

docs/getting-started/gs-credentials.md
docs/portal/api-keys.md
docs/portal/client-side-integration.md

mods to further differentiate between server-side values (API key etc) which are private and client-side values which are not.

mods to differentiate credential types

---

docs/getting-started/gs-encryption-decryption.md
i18n/ja/docusaurus-plugin-content-docs/current/getting-started/gs-encryption-decryption.md

Add the required optout_check 
https://unifiedid.com/docs/getting-started/gs-encryption-decryption
The code examples there for calling v2/token/generate doesn't have "optout_check:1" which we required for all new participants to add into the request since late last year.
 
We should specify like this:
echo '{"email": "sunny@example.com","optout_check":1}' | python3.10 uid2_request.py https://prod.uidapi.com/v2/token/generate .....

Add missing optout_check

---

docs/guides/integration-mobile-client-server.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-mobile-client-server.md

To client-server mobile doc section re Prebid, add note re required version

To mobile doc section re Prebid, add note re required version

---

docs/guides/integration-google-ss.md

Mods to UID2 GSS doc re three implementation approaches (from SW)
Note: I added the new section for the third implementation approach, which is a valid approach  now even though we don't have an integration example. But, it's basically the same copy. It uses the JS SDK... I linked to the correct JS implementation guide in each section, and linked to the sample implementation where it exists. Not sure of any other differences needed in the new section. Please provide input if applicable.

Mods to UID2 GSS doc re three implementation approaches (from SW)

---

docs/portal/sharing-permissions.md

In the UID2 Portal doc, add info re the Portal's sharing permission recommendations.

Portal, add info re recommended sharing permissions

---

docs/guides/integration-google-ss.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/integration-google-ss.md

To GSS doc, add client-side React sample implementation
(Same mods in Japanese file. No need to review both -- any edits I will apply to both files)

To GSS doc, add client-side React sample implementation

---

docs/sdks/uid2-sdk-ref-python.mdx

put back redirect file for Python SDK since there is an external link pointing to the old filename.

put back redirect file for Python SDK

---

i18n/ja/code.json
src/theme/NotFound/Content/index.tsx
src/theme/NotFound/index.tsx

- I ran the command to eject the `NotFound` theme component, allowing customization to 404 pages.
- Command run: `npm run swizzle @docusaurus/theme-classic NotFound`
- Changes to the file `src/theme/NotFound/Content/index.tsx` will be shown on the 404 page.

ibg-CORPWEB-3437-404-page

---

docs/guides/integration-prebid-client-side.md

make info re getting integ credentials more accessible

make info re getting integ credentials more accessible

---

docs/guides/integration-ctv-guide.md
docs/guides/integration-options-private-operator.md
docs/ref-info/glossary-uid.md

Minor edits to:
- CTV guide to make a bulleted list into a table.
- Glossary, modify secret salt > salt.
- UID2 Private Operator Integration Overview, minor fix.

minor edits CTV guide

---

src/theme/SiteMetadata/index.tsx

- sidebar.js generates alternate pages that end in -1, -2, .etc. This canonical href fix will prevent search engines from indexing those pages as unique and instead dedupe.

ibg-CORPWEB-3542-canonical-dedupe

---

docs/guides/operator-guide-aws-marketplace.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/operator-guide-aws-marketplace.md

AWS Private Operator guide, update link

AWS Private Operator guide, update link

---

docs/getting-started/gs-faqs.md

Add an FAQ re the Prebid value to use for the atype property, for Android SDK users.

FAQ add re prebid android atype value

---

docs/sdks/sdk-ref-java.md

Add intro copy in Java SDK doc section, to align with corresponding Python SDK doc section.

Add intro copy in Java SDK doc section

---

static/examples/cstg-prebid-example/index.html

Currently when users enter an opted out email in the prebid sample site, nothing happens. Updated functionality so user knows whats happening similar to how EUID prebid sample sites displays an opted out message.

Handle cases for opted out emails
